### ISSUE TITLE
请问需要提前准备好哪些文件夹和文件

### ISSUE THREAD

**Issue by liuyingqq123** [Banlangenn/banlg#3]
我现在准备了src->router->index.js和views->a文件夹
执行banlg  comName a parentComName b
提示[A]      父级组件没找到，请检查后再试

**Comment by Banlangenn** [comment]
banlg comName ?parentComName ?-t

* comName  你的组件名称
* parentComName  你的父组件名称 （可选的）
* -t    子路由文件是否插入父组件文件夹（可选的）
* 并且这个命令是和路由关系对应的
### 例如  
### banlg  a   （：创建 A组件）
### banlg b    a    （：创建 A 组件的 子路由 B组件）

```js
banlg comName  //（直接创建路由和组件文件和文件文件夹）
banlg comName parentComName  //（创建parentComName  的 comName 子路由）
banlg comName parentComName -t 
 //（创建parentComName  的 comName 子路由，并且文件放在parentComName  文件夹下边）
```
你在哪里看到这个东西的？

**Comment by liuyingqq123** [comment]
谢谢, 现在可以用了, 请问支持二级文件夹目录吗

**Comment by Banlangenn** [comment]
二级文件夹目录 - 是什么意思？？举个例子：  
banlg comName parentComName -t 
 //（创建parentComName  的 comName 子路由，并且文件放在parentComName  文件夹下边
不太确定这个是不是你想要的

**Comment by liuyingqq123** [comment]
例如views下的结构, 想默认生成
views
  --my
    --user
      --add.vue
      --query.vue
    --goods
      --add.vue
      --query.vue
  --other
    --centerinfo
      --add.vue
      --query.vue
    --cart
      --add.vue
      --query.vue

**Comment by liuyingqq123** [comment]
例如views下的结构, 想默认生成
views
--my
----user
------add.vue
------query.vue
----goods
------add.vue
------query.vue
--other
----centerinfo
------add.vue
------query.vue
----cart
------add.vue
------query.vue

**Comment by Banlangenn** [comment]
文件夹结构：同时还是要和路由对应的
----
你这个路由怎么办，文件三级，路由二级：命令不好描述的

**Comment by Banlangenn** [comment]
> 例如views下的结构, 想默认生成
> views
> --my
> ----user
> ------add.vue
> ------query.vue
> ----goods
> ------add.vue
> ------query.vue
> --other
> ----centerinfo
> ------add.vue
> ------query.vue
> ----cart
> ------add.vue
> ------query.vue

支持了目录结构--最新版本支持了，带路径的组件
